# Generated by Django 5.1.6 on 2025-02-24 01:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_cryptokey_message_createdat_message_receiver_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('createdat', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
